//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementApp.ProxyService.InventoryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryServiceReference.IInventoryService")]
    public interface IInventoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/GetProducts", ReplyAction="http://tempuri.org/IInventoryService/GetProductsResponse")]
        InventoryManagementApp.ProxyService.InventoryServiceReference.GetProductsResponse GetProducts(InventoryManagementApp.ProxyService.InventoryServiceReference.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/GetProducts", ReplyAction="http://tempuri.org/IInventoryService/GetProductsResponse")]
        System.Threading.Tasks.Task<InventoryManagementApp.ProxyService.InventoryServiceReference.GetProductsResponse> GetProductsAsync(InventoryManagementApp.ProxyService.InventoryServiceReference.GetProductsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProducts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductsRequest {
        
        public GetProductsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<InventoryManagementApp.Models.Product> GetProductsResult;
        
        public GetProductsResponse() {
        }
        
        public GetProductsResponse(System.Collections.Generic.List<InventoryManagementApp.Models.Product> GetProductsResult) {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInventoryServiceChannel : InventoryManagementApp.ProxyService.InventoryServiceReference.IInventoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryServiceClient : System.ServiceModel.ClientBase<InventoryManagementApp.ProxyService.InventoryServiceReference.IInventoryService>, InventoryManagementApp.ProxyService.InventoryServiceReference.IInventoryService {
        
        public InventoryServiceClient() {
        }
        
        public InventoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InventoryManagementApp.ProxyService.InventoryServiceReference.GetProductsResponse GetProducts(InventoryManagementApp.ProxyService.InventoryServiceReference.GetProductsRequest request) {
            return base.Channel.GetProducts(request);
        }
        
        public System.Threading.Tasks.Task<InventoryManagementApp.ProxyService.InventoryServiceReference.GetProductsResponse> GetProductsAsync(InventoryManagementApp.ProxyService.InventoryServiceReference.GetProductsRequest request) {
            return base.Channel.GetProductsAsync(request);
        }
    }
}
